# ErrnoException

## Hierarchy

- `Error`

  â†³ **`ErrnoException`**

## Properties

### cause

 `Optional` **cause**: `unknown`

#### Inherited from

Error.cause

#### Defined in

docs-util/node_modules/typescript/lib/lib.es2022.error.d.ts:24

___

### code

 `Optional` **code**: `string`

#### Defined in

docs-util/node_modules/@types/node/globals.d.ts:224

___

### errno

 `Optional` **errno**: `number`

#### Defined in

docs-util/node_modules/@types/node/globals.d.ts:223

___

### message

 **message**: `string`

#### Inherited from

Error.message

#### Defined in

docs-util/node_modules/typescript/lib/lib.es5.d.ts:1068

___

### name

 **name**: `string`

#### Inherited from

Error.name

#### Defined in

docs-util/node_modules/typescript/lib/lib.es5.d.ts:1067

___

### path

 `Optional` **path**: `string`

#### Defined in

docs-util/node_modules/@types/node/globals.d.ts:225

___

### stack

 `Optional` **stack**: `string`

#### Inherited from

Error.stack

#### Defined in

docs-util/node_modules/typescript/lib/lib.es5.d.ts:1069

___

### syscall

 `Optional` **syscall**: `string`

#### Defined in

docs-util/node_modules/@types/node/globals.d.ts:226
